language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -qq update
install:
  # Packages for building the website
  - sudo apt-get install -y pandoc
  - pip3 install pandocfilters pylint
  # Need a newer version of linkchecker then available from the apt channel
  - sudo apt install python-pip python-setuptools
  - pip2 install git+git://github.com/linkcheck/linkchecker.git@master
  # Node.js
  - nvm install --lts
  - npm install
script:
  - (cd .. && git clone https://github.com/pyta-uoft/pyta)
  - npm run build
  - npm run test
after_success:
  - npm run deploy
notifications:
  email: false
