sudo: false
language: python
python:
  - "3.6"
install:
  # Need a newer version of linkchecker then available from the apt channel
  - "wget http://ftp.debian.org/debian/pool/main/l/linkchecker/linkchecker_9.3-1+deb8u1_amd64.deb"
  - "sudo dpkg -i linkchecker_9.3-1+deb8u1_amd64.deb"
  - "pip install pylint funcparserlib colorama jinja2 pycodestyle hypothesis"
  - "nvm install --lts"
  - "npm install"
before_script:
  - "(cd .. && git clone https://github.com/pyta-uoft/pyta)"
script:
  - "npm build"
  - "npm test"
after_success:
  - "npm deploy"
notifications:
  email: false
