language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -qq update
install:
  # Packages for building the website
  - sudo apt-get install -y pandoc
  - pip3 install pandocfilters pylint
  # Need a newer version of linkchecker then available from the apt channel
  - sudo apt install python-pip python-setuptools
  - pip2 install git+git://github.com/linkcheck/linkchecker.git@8dc2963264b84babca3d501c195d470a58006ac0
  # Node.js
  - nvm install --lts
  - npm install -g 'remark@^8.0.0' 'remark-cli@^4.0.0' 'remark-lint@^6.0.0' 'remark-preset-lint-recommended@^3.0.0' 'gh-pages@^1.0.0'
script:
  - (cd .. && git clone https://github.com/pyta-uoft/pyta)
  - python build.py
  - remark index.md -f >/dev/null
  - linkchecker -v --check-extern gen/index.html
after_success:
  - gh-pages -d gen
notifications:
  email: false
