language: python
python:
  - "3.6"
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  # Need a newer version of linkchecker then available from the apt channel
  - wget http://ftp.debian.org/debian/pool/main/l/linkchecker/linkchecker_9.3-1+deb8u1_amd64.deb
  - sudo dpkg -i linkchecker_9.3-1+deb8u1_amd64.deb
  - nvm install --lts
  - pip install pandocfilters pylint
  - npm install
script:
  - (cd .. && git clone https://github.com/pyta-uoft/pyta)
  - npm run build
  - npm run test
after_success:
  - npm run deploy
notifications:
  email: false
